version: "3.7" 
services:   
  db:
    networks:
      new:
          aliases:
              - database
    restart: always
    container_name: db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=tutorcare_core
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    networks:
        - new
    volumes:
        - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://user:password@database:5432/tutorcare_core?sslmode=disable", "up"]
    links: 
        - db
  web:
    networks:
      - new
    build: . 
    ports:
      - "8080:8080"
    volumes:
      - .:/server
    links:
      - db
    depends_on:
      - db
      - redis
    environment:
      PORT: 8080
      CONNECTION_STRING_DEV: db://user:password@db:5433/db
      DSN: "db://user:password@db:5433/tutorcare_core"
  redis:
    networks:
      - new
    image: "redis"
    ports:
      - "6379:6379"
networks:
  new: