version: "3.7" 
services:   
  db:
    restart: always
    # image: postgres:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: tutorcare_core
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/server
    links:
      - db
    depends_on:
      - db
    environment:
      PORT: 8080
      CONNECTION_STRING_DEV: postgres://user:password@tutorcare_core/tutorcare_core