SET TIMEZONE='US/Eastern';
CREATE TABLE IF NOT EXISTS post_codes(post_id INT NOT NULL, code_id INT GENERATED ALWAYS AS IDENTITY, code INT NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE, timestamp TIMESTAMPTZ DEFAULT now(), PRIMARY KEY (code_id), CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES posts(post_id));
